elevation_mapping:
  ros__parameters:
    fused_output_topic: ""
    output_topic: elevation_map
    output_layers: [elevation, step, slope, rough, p_unknown]
  
    postprocessor_pipeline: # set by postprocessor_pipeline_name
      # Fill holes in the map with inpainting.
      filter1:
        name: inpaint
        type: gridMapCv/InpaintFilter
        params:
          input_layer: elevation
          output_layer: elevation_inpainted
          radius: 0.05

      #  Delete layers that are not needed to reduce bandwidth
      # filter3:
      #   name: delete_original_layers
      #   type: gridMapFilters/DeletionFilter
      #   params:
      #     layers: [lowest_scan_point,sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan] # List of layers.
